source "https://rubygems.org"
ruby '3.2.2'
gem "fastlane"
gem 'cocoapods', '1.15.2'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
